Pass callback to the jQuery method
Yoast/yoast-test-helper pull request #112
Opened 2020-11-30 08:32 UTC by andizer

## Summary

This PR can be summarized in the following changelog entry:

* Fixes a bug where a deprecated jQuery function was used.

## Relevant technical choices:

*

## Milestone

* [ ] I've attached the next release's milestone to this pull request.

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* On `trunk`
* Install the `Enable jQuery Migrate Helper` plugin made by WordPress
* Navigate to the test helper page and see an error is given
* Checkout this branch
* See that the test helper isn't given an error.
* Merge 
### Test instructions for QA when the code is in the RC

* [x] QA should use the same steps as above.

QA can test this PR by following these steps:

*

Fixes #

2020-11-30 12:02 UTC, hansjovis requested changes
CR: 🚫 

jQuery suggests fixing it differently.

2020-11-30 12:25 UTC, andizer commented on src/admin-page.php
> +			jQuery( function() {
I just followed the implementation we've used at other places in the Yoast SEO plugin. I am fine with this 👍

2020-11-30 12:33 UTC, andizer commented
Regression testing isn't that easy, because on older version of WordPress no errors will be given. The migrate class is causing this error. I would say for this fix the step should be enough.

2020-11-30 13:30 UTC, increddibelly approved these changes

2020-12-01 08:14 UTC, hansjovis approved these changes

2020-12-01 08:19 UTC, hansjovis commented
With regression testing I meant that we should still test whether the functionality that it touches still works as expected.

In this case this would be that the Masonry script still loads on window load and the layout of the test helper page is still as it used to be.

2020-12-01 08:33 UTC, hansjovis commented
Acceptance test: ✅ 

* Warning is gone.
* Layout is still as expected:
<img width="1341" alt="Screenshot 2020-12-01 at 09 30 20" src="https://user-images.githubusercontent.com/10195175/100715938-41733380-33b8-11eb-88b7-56d7b7fb0ec3.png">

2020-12-01 08:34 UTC, merged